# Generated by Django 4.2.9 on 2024-03-12 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('gas_leak', 'Gas Leak'), ('meter_installation', 'Meter Installation'), ('meter_repair', 'Meter Repair'), ('account_update', 'Account Update'), ('billing_issue', 'Billing Issue'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=50)),
                ('details', models.TextField()),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='service_request_files/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
